table HistoricalConcreteBenchmark
	lineageTag: e3e8ab5c-f3ff-4d0a-a8a0-7622492e6d9a

	column ConcreteTestDataId
		dataType: int64
		formatString: 0
		lineageTag: 4365940f-0665-4682-a2d2-0aef7f3f0560
		summarizeBy: count
		sourceColumn: ConcreteTestDataId

		annotation SummarizationSetBy = Automatic

	column TestId
		dataType: int64
		formatString: 0
		lineageTag: 57eac515-7543-4f31-95e9-bfb9765ec623
		summarizeBy: count
		sourceColumn: TestId

		annotation SummarizationSetBy = Automatic

	column SampleId
		dataType: int64
		formatString: 0
		lineageTag: 1d4a6c54-8fa5-4ce3-b768-26c704f905a4
		summarizeBy: count
		sourceColumn: SampleId

		annotation SummarizationSetBy = Automatic

	column LabNo
		dataType: string
		lineageTag: c97328af-bdd6-4f75-8692-89014b01eae7
		summarizeBy: none
		sourceColumn: LabNo

		annotation SummarizationSetBy = Automatic

	column OfficeId
		dataType: int64
		formatString: 0
		lineageTag: 6539c53f-7dc5-4be4-92ea-093a5ce8aa28
		summarizeBy: count
		sourceColumn: OfficeId

		annotation SummarizationSetBy = Automatic

	column OfficeName
		dataType: string
		lineageTag: 3ce802de-5e02-40c8-8d3d-9d83b083199c
		summarizeBy: none
		sourceColumn: OfficeName

		annotation SummarizationSetBy = Automatic

	column ProjectId
		dataType: int64
		formatString: 0
		lineageTag: f8d8d10c-6eb8-4672-aba4-3575ce6348e4
		summarizeBy: count
		sourceColumn: ProjectId

		annotation SummarizationSetBy = Automatic

	column ProjectNo
		dataType: string
		lineageTag: a6d67c7b-8a76-460c-93e2-fedae3334a98
		summarizeBy: none
		sourceColumn: ProjectNo

		annotation SummarizationSetBy = Automatic

	column ProjectName
		dataType: string
		lineageTag: 9804880e-49d4-4c43-b0fc-4181d623c5bc
		summarizeBy: none
		sourceColumn: ProjectName

		annotation SummarizationSetBy = Automatic

	column TestSubTypeId
		dataType: int64
		formatString: 0
		lineageTag: 555d86a1-c0de-497b-8dce-bb18eb2eeb3b
		summarizeBy: count
		sourceColumn: TestSubTypeId

		annotation SummarizationSetBy = Automatic

	column ConcreteTestUnitSystem
		dataType: int64
		formatString: 0
		lineageTag: 79413c71-86d5-4e36-8ba9-dc344ee43232
		summarizeBy: sum
		sourceColumn: ConcreteTestUnitSystem

		annotation SummarizationSetBy = Automatic

	column CastDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: e9d377e3-0dbd-4873-9baf-f68c07e2b48d
		summarizeBy: none
		sourceColumn: CastDate

		variation Variation
			isDefault
			relationship: 15d12daf-27d9-4248-95f9-4d25e3173515
			defaultHierarchy: LocalDateTable_ad7e361d-5a76-4262-9598-5659dfcc6c94.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PlacementType
		dataType: string
		lineageTag: 6fa63579-846c-486e-8299-179151d014d0
		summarizeBy: none
		sourceColumn: PlacementType

		annotation SummarizationSetBy = Automatic

	column PlacementLocation
		dataType: string
		lineageTag: 39bbc218-606d-45ca-8768-6860052d2bee
		summarizeBy: none
		sourceColumn: PlacementLocation

		annotation SummarizationSetBy = Automatic

	column SampledFrom
		dataType: string
		lineageTag: cb2cc2bb-d6ec-458d-81be-5095d7de1b69
		summarizeBy: none
		sourceColumn: SampledFrom

		annotation SummarizationSetBy = Automatic

	column SupplierId
		dataType: int64
		formatString: 0
		lineageTag: c6f9396d-760b-4796-b628-0a7854b48ada
		summarizeBy: count
		sourceColumn: SupplierId

		annotation SummarizationSetBy = Automatic

	column SupplierName
		dataType: string
		lineageTag: f9a3ae70-e1f1-4b00-9f9c-c50672c9f4ca
		summarizeBy: none
		sourceColumn: SupplierName

		annotation SummarizationSetBy = Automatic

	column PlantNumber
		dataType: string
		lineageTag: 9460475c-0662-48ff-93c3-5ed3a9976784
		summarizeBy: none
		sourceColumn: PlantNumber

		annotation SummarizationSetBy = Automatic

	column MixNumber
		dataType: string
		lineageTag: f5c174bd-cfd0-41f3-90b6-ba230ea466cc
		summarizeBy: none
		sourceColumn: MixNumber

		annotation SummarizationSetBy = Automatic

	column TruckNumber
		dataType: string
		lineageTag: d8128d1a-83ce-4a2e-8d4b-ea44568042eb
		summarizeBy: none
		sourceColumn: TruckNumber

		annotation SummarizationSetBy = Automatic

	column TicketNumber
		dataType: string
		lineageTag: df13c5c4-7e11-4108-b9ec-8a62ec80b5ac
		summarizeBy: none
		sourceColumn: TicketNumber

		annotation SummarizationSetBy = Automatic

	column SampleWorkflowStateId
		dataType: int64
		formatString: 0
		lineageTag: dec5e6b0-b452-483a-a361-f5fc27e84e3f
		summarizeBy: count
		sourceColumn: SampleWorkflowStateId

		annotation SummarizationSetBy = Automatic

	column TestWorkflowStateId
		dataType: int64
		formatString: 0
		lineageTag: 66551aa3-7957-48c0-8a11-d5f0a42e228e
		summarizeBy: count
		sourceColumn: TestWorkflowStateId

		annotation SummarizationSetBy = Automatic

	column UnapprovedReportCount
		dataType: int64
		formatString: 0
		lineageTag: 2001a807-9725-4c12-9463-dbc6e9bc5191
		summarizeBy: sum
		sourceColumn: UnapprovedReportCount

		annotation SummarizationSetBy = Automatic

	column AmendmentNumber
		dataType: int64
		formatString: 0
		lineageTag: cd31ceb5-f3d3-47df-9b8f-cd21ef01ce36
		summarizeBy: sum
		sourceColumn: AmendmentNumber

		annotation SummarizationSetBy = Automatic

	column LastAmendDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 86393944-96bc-4cbd-8342-55734f56d8b7
		summarizeBy: none
		sourceColumn: LastAmendDate

		variation Variation
			isDefault
			relationship: ef97bcf1-d32c-44f3-ba4f-55c2ad445964
			defaultHierarchy: LocalDateTable_abf677c0-51eb-4b77-8458-792f75e0c05b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column RequiresAmendment
		dataType: int64
		formatString: 0
		lineageTag: b10c9258-a261-4f24-ae61-7c6e1bc29d99
		summarizeBy: sum
		sourceColumn: RequiresAmendment

		annotation SummarizationSetBy = Automatic

	column AllBreaksCompleted
		dataType: int64
		formatString: 0
		lineageTag: dac66e39-6c95-4101-a1e7-02ab832cc855
		summarizeBy: sum
		sourceColumn: AllBreaksCompleted

		annotation SummarizationSetBy = Automatic

	column EffectiveSlump_in
		dataType: double
		lineageTag: da384b44-4347-4c53-b173-c2b4ee207041
		summarizeBy: sum
		sourceColumn: EffectiveSlump_in

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SlumpMeasurementSource
		dataType: string
		lineageTag: 14c70e08-3179-49e0-ba98-ffa593273fbd
		summarizeBy: none
		sourceColumn: SlumpMeasurementSource

		annotation SummarizationSetBy = Automatic

	column SlumpSpecMin_in
		dataType: double
		lineageTag: f4b2f7aa-7aa9-47b6-b7f8-69ce895df164
		summarizeBy: sum
		sourceColumn: SlumpSpecMin_in

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SlumpSpecMax_in
		dataType: double
		lineageTag: afc470c6-98f5-4b94-b852-a2738f47b424
		summarizeBy: sum
		sourceColumn: SlumpSpecMax_in

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EffectiveSpread_in
		dataType: double
		lineageTag: f08fab6f-be0e-45b8-a592-b7cce06867fb
		summarizeBy: sum
		sourceColumn: EffectiveSpread_in

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SpreadMeasurementSource
		dataType: string
		lineageTag: b6ea3a26-fb10-487c-9974-9c94c63037f7
		summarizeBy: none
		sourceColumn: SpreadMeasurementSource

		annotation SummarizationSetBy = Automatic

	column SpreadSpecMin_in
		dataType: double
		lineageTag: 2660df3a-5046-420a-ac64-dc70ac7ffbe5
		summarizeBy: sum
		sourceColumn: SpreadSpecMin_in

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SpreadSpecMax_in
		dataType: double
		lineageTag: f81e36e1-1543-45cd-b504-dad3d0a193c5
		summarizeBy: sum
		sourceColumn: SpreadSpecMax_in

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EffectiveAir_percent
		dataType: double
		lineageTag: 333da881-d621-47d9-b082-232acfdfa7ea
		summarizeBy: sum
		sourceColumn: EffectiveAir_percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AirMeasurementSource
		dataType: string
		lineageTag: 4f3787f9-77f7-4133-821c-c60894f3102c
		summarizeBy: none
		sourceColumn: AirMeasurementSource

		annotation SummarizationSetBy = Automatic

	column AirSpecMin_percent
		dataType: double
		lineageTag: e1e803e4-3579-4c90-bb84-531f8d48ddcf
		summarizeBy: sum
		sourceColumn: AirSpecMin_percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AirSpecMax_percent
		dataType: double
		lineageTag: a01d51e7-f898-492f-a4ab-aaa88c273e24
		summarizeBy: sum
		sourceColumn: AirSpecMax_percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EffectiveUnitWeight_lb_ft3
		dataType: double
		lineageTag: 04544e64-f93d-42aa-bc7f-019ba29e2607
		summarizeBy: sum
		sourceColumn: EffectiveUnitWeight_lb_ft3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitWeightMeasurementSource
		dataType: string
		lineageTag: 431e40b4-a3e5-4342-a579-780a4a31611f
		summarizeBy: none
		sourceColumn: UnitWeightMeasurementSource

		annotation SummarizationSetBy = Automatic

	column UnitWeightSpecMin_lb_ft3
		dataType: double
		lineageTag: 9118954a-8a58-4df1-a959-d0f78f33aac4
		summarizeBy: sum
		sourceColumn: UnitWeightSpecMin_lb_ft3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitWeightSpecMax_lb_ft3
		dataType: double
		lineageTag: 8a9a6730-8785-46bc-84d6-57f04e359620
		summarizeBy: sum
		sourceColumn: UnitWeightSpecMax_lb_ft3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EffectiveConcreteTemp_F
		dataType: double
		lineageTag: 1377f6fc-bd1d-48dd-aa60-5c623e13f914
		summarizeBy: sum
		sourceColumn: EffectiveConcreteTemp_F

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ConcreteTempMeasurementSource
		dataType: string
		lineageTag: 19f5f1ef-b0ad-42ba-9e86-bd3a45232e7e
		summarizeBy: none
		sourceColumn: ConcreteTempMeasurementSource

		annotation SummarizationSetBy = Automatic

	column ConcreteTempSpecMin_F
		dataType: double
		lineageTag: 70d57a79-d39f-4a43-96aa-a7b14d2bdb94
		summarizeBy: sum
		sourceColumn: ConcreteTempSpecMin_F

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ConcreteTempSpecMax_F
		dataType: double
		lineageTag: fa49a196-a11e-4c62-b09f-8eda289ef181
		summarizeBy: sum
		sourceColumn: ConcreteTempSpecMax_F

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AmbientTemp_F
		dataType: double
		lineageTag: c4f781d5-744c-479d-b821-8cb7cbdfb76f
		summarizeBy: sum
		sourceColumn: AmbientTemp_F

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column InitialCuringHighTemp_F
		dataType: double
		lineageTag: e81c65fa-3afc-4c95-b43d-cb9d0672ec93
		summarizeBy: sum
		sourceColumn: InitialCuringHighTemp_F

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column InitialCuringLowTemp_F
		dataType: double
		lineageTag: 56f8d7fe-ab54-4445-948b-9493713f6a02
		summarizeBy: sum
		sourceColumn: InitialCuringLowTemp_F

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column InitialCuringCondition
		dataType: string
		lineageTag: 24cacca1-c780-46d8-99fe-6b89f3340e54
		summarizeBy: none
		sourceColumn: InitialCuringCondition

		annotation SummarizationSetBy = Automatic

	column BatchTime
		dataType: dateTime
		formatString: Long Time
		lineageTag: 011a219a-643c-434d-a70d-71e2a6119d51
		summarizeBy: none
		sourceColumn: BatchTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column SampleTime
		dataType: dateTime
		formatString: Long Time
		lineageTag: b062f432-e066-493e-98d0-7ba3907d095e
		summarizeBy: none
		sourceColumn: SampleTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column CastTime
		dataType: dateTime
		formatString: Long Time
		lineageTag: 428b8dc4-ad3c-43dd-8ad9-27d2db1f0d13
		summarizeBy: none
		sourceColumn: CastTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column WaterAddedRaw
		dataType: double
		lineageTag: ea638d7b-6b3e-42cb-9bc5-63d292c652ea
		summarizeBy: sum
		sourceColumn: WaterAddedRaw

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LoadBatchVolumeRaw
		dataType: double
		lineageTag: 21e60f41-0825-4da8-bfb6-0d55197c4559
		summarizeBy: sum
		sourceColumn: LoadBatchVolumeRaw

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LoadVolumeUnits
		dataType: string
		lineageTag: 097c0674-7be8-4241-b13d-3e8c52e6aed6
		summarizeBy: none
		sourceColumn: LoadVolumeUnits

		annotation SummarizationSetBy = Automatic

	column TestSpecifiedStrengthRaw
		dataType: double
		lineageTag: e3649dd3-dcb9-4f3d-acbd-fd1725aeca9c
		summarizeBy: sum
		sourceColumn: TestSpecifiedStrengthRaw

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TestSpecifiedStrengthDaysRaw
		dataType: int64
		formatString: 0
		lineageTag: 88d8da6b-eac3-4ae4-8e23-b723d742e5b3
		summarizeBy: sum
		sourceColumn: TestSpecifiedStrengthDaysRaw

		annotation SummarizationSetBy = Automatic

	column TestSpecifiedStrengthTypeIdRaw
		dataType: int64
		formatString: 0
		lineageTag: c88a220c-fb61-4616-bf9c-76e1371f6bca
		summarizeBy: sum
		sourceColumn: TestSpecifiedStrengthTypeIdRaw

		annotation SummarizationSetBy = Automatic

	column RequiredStrength28_psi
		dataType: double
		lineageTag: 62378769-ee61-4a6d-8c7a-54b17c446ae9
		summarizeBy: sum
		sourceColumn: RequiredStrength28_psi

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RequiredStrength28RowCount
		dataType: int64
		formatString: 0
		lineageTag: 19d0784a-deab-4d88-a2a3-dd4cc5a0b61f
		summarizeBy: sum
		sourceColumn: RequiredStrength28RowCount

		annotation SummarizationSetBy = Automatic

	column RequiredStrength28DistinctValueCount
		dataType: int64
		formatString: 0
		lineageTag: 2dd968c2-47cd-416d-9030-484f48c323dd
		summarizeBy: sum
		sourceColumn: RequiredStrength28DistinctValueCount

		annotation SummarizationSetBy = Automatic

	column DesignStrength28_psi
		dataType: double
		lineageTag: 62a0ee71-6881-4296-8931-cf181e071108
		summarizeBy: sum
		sourceColumn: DesignStrength28_psi

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DesignStrength28RowCount
		dataType: int64
		formatString: 0
		lineageTag: 44698f4b-6233-4137-a21f-eadbabfd9e39
		summarizeBy: sum
		sourceColumn: DesignStrength28RowCount

		annotation SummarizationSetBy = Automatic

	column DesignStrength28DistinctValueCount
		dataType: int64
		formatString: 0
		lineageTag: 7628928e-296e-435d-b295-f41111c2100f
		summarizeBy: sum
		sourceColumn: DesignStrength28DistinctValueCount

		annotation SummarizationSetBy = Automatic

	column ConcreteTestLastUpdatedAt
		dataType: dateTime
		formatString: General Date
		lineageTag: 0b9dd5a6-06f0-4d5f-a160-2148ba357dbe
		summarizeBy: none
		sourceColumn: ConcreteTestLastUpdatedAt

		variation Variation
			isDefault
			relationship: 284082ae-57d1-4b3f-aa89-9facd9dd2321
			defaultHierarchy: LocalDateTable_d84fba02-fed4-482f-aa17-f0f483f9fb3a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column BreakAgeDays
		dataType: int64
		formatString: 0
		lineageTag: 1eeaba42-bb4e-40af-9a7f-255bcec9a661
		summarizeBy: sum
		sourceColumn: BreakAgeDays

		annotation SummarizationSetBy = Automatic

	column CuringType
		dataType: string
		lineageTag: 3a28a489-5649-4b73-b9a2-e4a03a7c586b
		summarizeBy: none
		sourceColumn: CuringType

		annotation SummarizationSetBy = Automatic

	column TestAverageStrength_psi
		dataType: double
		lineageTag: 320af36c-37ed-4a8d-b44d-85e6bfe835e0
		summarizeBy: sum
		sourceColumn: TestAverageStrength_psi

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SpecimensWithResults
		dataType: int64
		formatString: 0
		lineageTag: d42174be-b6d5-4a46-a137-a79a72105da6
		summarizeBy: sum
		sourceColumn: SpecimensWithResults

		annotation SummarizationSetBy = Automatic

	partition HistoricalConcreteBenchmark = m
		mode: import
		source =
				let
				    Source = ConcreteTestHistory,
				    #"Merged Queries" = Table.NestedJoin(Source, {"ConcreteTestDataId"}, HistoricalStrengthSummaryPQ, {"ConcreteTestDataId"}, "HistoricalStrengthSummaryPQ", JoinKind.LeftOuter),
				    #"Expanded HistoricalStrengthSummaryPQ" = Table.ExpandTableColumn(#"Merged Queries", "HistoricalStrengthSummaryPQ", {"BreakAgeDays", "CuringType", "TestAverageStrength_psi", "SpecimensWithResults"}, {"HistoricalStrengthSummaryPQ.BreakAgeDays", "HistoricalStrengthSummaryPQ.CuringType", "HistoricalStrengthSummaryPQ.TestAverageStrength_psi", "HistoricalStrengthSummaryPQ.SpecimensWithResults"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Expanded HistoricalStrengthSummaryPQ",{{"HistoricalStrengthSummaryPQ.BreakAgeDays", "BreakAgeDays"}, {"HistoricalStrengthSummaryPQ.CuringType", "CuringType"}, {"HistoricalStrengthSummaryPQ.TestAverageStrength_psi", "TestAverageStrength_psi"}, {"HistoricalStrengthSummaryPQ.SpecimensWithResults", "SpecimensWithResults"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

